### PR TITLE
Fix the large block model, and the lighting bug with the old model

### PR DESCRIPTION
**Pull request by AlexIIL**
This has the texture bound properly, and the pearl has a proper texture bound too (Not sure if you had that before). I also lowered the triangle count considerably (even my laptop was struggling when breaking or placing small numbers of anchored pearls)

The texture is not complete, I thought that was best left up to you to re-texture however you wanted.

Current model:
screenshot from 2015-11-16 22 29 37
screenshot from 2015-11-16 22 32 01
screenshot from 2015-11-16 22 32 14
screenshot from 2015-11-16 22 32 25
screenshot from 2015-11-16 21 42 41

### CODE REVIEW

**Comment by AlexIIL** [comment]
I would recommend testing this though, just to make sure you are happy with the model before you texture. I also made the chunk loader blocks emit (full) light to fix a bug where if you placed a block directly above the centre of the model it would be completely black on all the top-facing sides.

**Comment by AlexIIL** [comment]
Also, I think you can close MinecraftForge/MinecraftForge#2188 as that was probably just caused by a bad model file.

**Comment by AEnterprise** [comment]
thanks alot :) any idea what the cause for the bad model file might have been?

**Comment by AlexIIL** [comment]
Probably that the model had overlapping faces- opening it up in blender, some (well, most) of the faces had another one in occupying the same place (causing depth-fighting) and they had different textures, so it looked strange.

**Comment by AEnterprise** [comment]
@AlexIIL would you be interested in working with me on other models in the future?

**Comment by AlexIIL** [comment]
Sure! However I won't be _quite_ as quick to make them (the big model took 2 days) and I'm currently kinda behind with my BC port. Admittedly 1 day was taken up by finding out that techne doesn't work on windows 10, and tabula wasn't working either.

**Comment by AlexIIL** [comment]
Although if its a less complex model than that, then sure :)

**Comment by AEnterprise** [comment]
alright good to know :)

**Pull request merged**
